server:
  port: 8080
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: h2
#    database: mariadb
  datasource:
    url: "jdbc:h2:mem:testdb"
#    url: "jdbc:mariadb://localhost:___"
    username: root
    password: root
  h2:
    console:
      enabled: true
      path: "/h2-console"
logging:
  level:
    root: debug